@server = http://localhost:4004
@auth = Authorization: Basic alice:


### Main.Alunos
GET {{server}}/main/Alunos?$expand=avaliacoes
Content-Type: application/json
{{auth}}

### Main.Alunos
POST {{server}}/main/Alunos
Content-Type: application/json
{{auth}}

{
  "nome": "Renan",
  "dataNasc": "2013-12-30"
}

### Main.Alunos
PATCH  {{server}}/main/Alunos(7814ff38-2ea8-4afe-a9ff-da2781810038)
Content-Type: application/json
{{auth}}

{
  "nome": "João",
  "dataNasc": "2013-12-30"
}

### Main.Avaliacoes
GET {{server}}/main/Avaliacoes?$expand=aluno
Content-Type: application/json
{{auth}}

### Main.Avaliacoes
POST {{server}}/main/Avaliacoes
Content-Type: application/json
{{auth}}

{
  "bimestre": 1,
  "nome": "Inglês",
  "tipo": "Teste",
  "peso": 1,
  "nota": 6,
  "aluno_ID": "199d4606-7bc3-409a-91e4-b7a562d5762e"
}

### Main.Boletins
GET {{server}}/main/Boletins
Content-Type: application/json
{{auth}}

### Main.Boletins
GET {{server}}/main/Boletins(aluno_ID=bd66a1f6-7c25-4f0f-b852-42901d1dcdac,bimestre=1,disciplina='Matemática')
Content-Type: application/json
{{auth}}

### Main.Boletins
GET {{server}}/main/Boletins(aluno_ID=bd66a1f6-7c25-4f0f-b852-42901d1dcdac,disciplina='Matemática')
Content-Type: application/json
{{auth}}

### Main.Boletins
POST  {{server}}/main/Boletins
Content-Type: application/json
{{auth}}

{
  "bimestre": 3,
  "disciplina": "Química",
  "media": 91.6
}
