@server = http://localhost:4004
@auth = Authorization: Basic alice:


### Main.Alunos
GET {{server}}/main/Alunos?$expand=avaliacoes
Content-Type: application/json
{{auth}}

### Main.Alunos
POST {{server}}/main/Alunos
Content-Type: application/json
{{auth}}

{
  "nome": "Renan",
  "dataNasc": "2013-12-30"
}

### Main.Avaliacoes
GET {{server}}/main/Avaliacoes?$expand=aluno
Content-Type: application/json
{{auth}}

### Main.Avaliacoes
POST {{server}}/main/Avaliacoes
Content-Type: application/json
{{auth}}

{
  "bimestre": 1,
  "nome": "Inglês",
  "tipo": "Prova",
  "peso": 1,
  "nota": 8.50,
  "aluno_ID": "67c9b530-827c-4774-ad85-7e53a73e90c2"
}

